[package]
name = 'shtest'
slug = 'shtest'
version = ''
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = ''

[run]
dependencies = ['https://github.com/hyperupcall/bats-common-utils.git@v3.0.1']
sourceDirs = []
builtinDirs = []
binDirs = ['bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
