[package]
name = 'shelltest'
slug = 'shelltest'
version = 'v0.1.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'A POSIX test runner'

[run]
dependencies = ['https://github.com/hyperupcall/bats-all.git@v4.3.0']
sourceDirs = []
builtinDirs = []
binDirs = ['bin']
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
